# .github/workflows/block-merge-if-vulnerabilities.yml
name: Block merge if 'Vulnerability Found' issues exist

on:
  pull_request:
    # runs for PRs targeting any branch (good)
    types: [opened, synchronize, reopened, edited, ready_for_review, labeled, unlabeled]
  push:
    branches: [main, dev]     # <-- ensure the job runs on dev too
  workflow_dispatch:          # <-- lets you Run workflow from Actions UI

permissions:
  contents: read
  pull-requests: read
  issues: read

jobs:
  check-vulnerability-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for override label
        id: check_override
        uses: actions/github-script@v7
        with:
          script: |
            const labels = (context.payload.pull_request?.labels || []).map(l => l.name);
            core.info(`PR labels: ${labels.join(', ') || '(none)'}`);
            const hasOverride = labels.includes('override-vulnerability-check');
            core.setOutput('override', hasOverride ? 'true' : 'false');

      - name: Check for open vulnerability issues
        if: steps.check_override.outputs.override == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const label = 'Vulnerability Found';
            const q = `repo:${owner}/${repo} is:issue is:open label:"${label}"`;
            const res = await github.rest.search.issuesAndPullRequests({ q, per_page: 1 });
            const openCount = res.data.total_count;
            core.info(`Open '${label}' issues: ${openCount}`);
            if (openCount > 0) {
              core.setFailed(`❌ Merge blocked: ${openCount} open issue(s) labeled '${label}' found.`);
            } else {
              core.notice('✅ No open vulnerability issues found — merge allowed.');
            }

      - name: Override active
        if: steps.check_override.outputs.override == 'true'
        run: echo "⚠️ Override label applied — skipping vulnerability issue check."
